
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x95D\x9fE\xa9\xb0\xdc\x98\t\x10\xeeh\xcc\x01\xac\xa8'
    
_lr_action_items = {'RCBR':([10,15,23,29,34,38,42,58,62,63,],[-18,-15,-20,-17,48,-23,-19,-16,-21,-22,]),'RABR':([40,41,54,],[53,-26,-25,]),'LSBR':([35,39,47,],[49,49,49,]),'RPAREN':([21,43,51,52,53,65,],[38,-27,62,63,-24,-28,]),'NAME':([0,4,5,6,7,10,11,13,14,15,18,23,25,26,27,29,34,38,42,46,49,55,58,59,60,61,62,63,64,66,67,69,],[1,8,-12,17,20,-18,28,31,33,-15,33,-20,43,-14,44,-17,33,-23,-19,43,59,-13,-16,64,59,-30,-21,-22,67,-29,68,-31,]),'LABR':([8,17,28,33,39,],[22,22,22,22,22,]),'NUMBER':([48,],[58,]),'TIP':([4,5,6,10,11,15,18,23,29,38,42,46,58,62,63,],[12,-12,19,-18,30,-15,37,-20,-17,-23,-19,56,-16,-21,-22,]),'EQUAL':([1,],[5,]),'REPLACE':([9,],[27,]),'ATTACH':([4,5,],[9,-12,]),'LCBR':([4,5,6,10,11,14,15,18,23,29,34,38,42,58,62,63,],[14,-12,14,-18,14,14,-15,14,-20,-17,14,-23,-19,-16,-21,-22,]),'COMMA':([8,16,20,21,31,32,43,],[25,35,25,39,46,47,-27,]),'LPAREN':([2,4,5,8,13,17,24,26,28,33,36,45,53,55,],[7,-11,-12,7,-10,7,7,-14,7,7,7,7,-24,-13,]),'COLON':([9,44,],[26,55,]),'ANGLE':([68,],[69,]),'LABEL':([22,40,41,54,],[41,54,-26,-25,]),'RSBR':([60,61,66,69,],[65,-30,-29,-31,]),'$end':([3,12,19,30,36,37,45,50,53,56,57,65,],[0,-7,-2,-6,-3,-1,-8,-9,-24,-5,-4,-28,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'angle':([49,60,],[61,66,]),'conf':([35,39,47,],[50,52,57,]),'segment':([4,6,11,14,18,34,],[10,10,29,10,29,29,]),'segments':([4,6,14,],[11,18,34,]),'labels':([22,],[40,]),'tag':([8,17,28,33,39,],[24,36,45,24,51,]),'attach':([4,],[13,]),'connection':([2,8,17,24,28,33,36,45,],[6,23,23,42,23,23,42,42,]),'base':([0,],[2,]),'branch':([0,],[3,]),'angles':([49,],[60,]),'root':([0,],[4,]),'block':([4,6,11,14,18,34,],[15,15,15,15,15,15,]),'bond':([4,7,13,],[16,21,32,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> branch","S'",1,None,None,None),
  ('branch -> base connection segments TIP','branch',4,'p_branch9','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',19),
  ('branch -> base connection TIP','branch',3,'p_branch8','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',23),
  ('branch -> base connection NAME tag','branch',4,'p_branch7','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',27),
  ('branch -> root attach bond COMMA conf','branch',5,'p_branch6','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',31),
  ('branch -> root attach NAME COMMA TIP','branch',5,'p_branch5','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',35),
  ('branch -> root segments TIP','branch',3,'p_branch4','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',39),
  ('branch -> root TIP','branch',2,'p_branch3','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',43),
  ('branch -> root segments NAME tag','branch',4,'p_branch2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',47),
  ('branch -> root bond COMMA conf','branch',4,'p_branch1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',52),
  ('base -> root attach','base',2,'p_base2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',56),
  ('base -> root','base',1,'p_base1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',60),
  ('root -> NAME EQUAL','root',2,'p_root','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',64),
  ('attach -> ATTACH REPLACE NAME COLON','attach',4,'p_attach2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',68),
  ('attach -> ATTACH COLON','attach',2,'p_attach1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',72),
  ('segment -> block','segment',1,'p_block2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',76),
  ('block -> LCBR segments RCBR NUMBER','block',4,'p_block1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',80),
  ('segments -> segments segment','segments',2,'p_segments2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',84),
  ('segments -> segment','segments',1,'p_segments1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',88),
  ('segment -> NAME tag connection','segment',3,'p_segment2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',92),
  ('segment -> NAME connection','segment',2,'p_segment1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',97),
  ('connection -> LPAREN bond COMMA tag RPAREN','connection',5,'p_connection3','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',101),
  ('connection -> LPAREN bond COMMA conf RPAREN','connection',5,'p_connection2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',106),
  ('connection -> LPAREN bond RPAREN','connection',3,'p_connection1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',110),
  ('tag -> LABR labels RABR','tag',3,'p_tag','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',114),
  ('labels -> labels LABEL','labels',2,'p_labels2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',118),
  ('labels -> LABEL','labels',1,'p_labels1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',122),
  ('bond -> NAME COMMA NAME','bond',3,'p_bond','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',126),
  ('conf -> LSBR angles RSBR','conf',3,'p_conf','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',130),
  ('angles -> angles angle','angles',2,'p_angles2','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',134),
  ('angles -> angle','angles',1,'p_angles1','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',138),
  ('angle -> NAME NAME NAME NAME ANGLE','angle',5,'p_angle','/media/data3/CHETAN/doglycan/CD59/pymtools/seqparse.py',142),
]
